return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
      auto_install = true,
      ensure_installed = {
        "css",
        "html",
        "javascript",
        "json",
        "lua",
        "rust",
        "typescript",
        "vim",
        "vue",
        "scss",
        "markdown",
        "markdown_inline",
        "yaml",
        "vimdoc",
        "go",
        "python",
        "ini",
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    },
    opts_extend = { "ensure_installed" },
  },
}
